@url=http://localhost:5000

POST {{url}}/users
Content-Type: application/json

{
    "email": "test@test.pl",
    "username": "test",
    "fullname": "test test",
    "password": "pwd123",
    "role": "user"
}

###

# @name sign_in
POST {{url}}/users/sign-in
Content-Type: application/json

{
    "email": "test@test.pl",
    "password": "pwd123"
}

###

@accessToken={{sign_in.response.body.$.accessToken}}

### 

GET {{url}}/users/me
Authorization: Bearer {{accessToken}}