@url=http://localhost:5000

POST {{url}}/reservations
Content-Type: application/json

{
    "parkingSpotId": "00000000-0000-0000-0000-000000000001",
    "date": "2022-01-02",
    "employeeName": "Anim Macin",
    "licencePlate": "XYZ"
}