@url=http://localhost:5000

POST {{url}}/reservations
Content-Type: application/json

{
    "employeeName": "Anic",
    "licencePlate": "WW 092YX",
    "parkingSpotName": "P1",
    "date": "2022-01-02T00:00:00Z"
}