@url=http://localhost:5000

POST {{url}}/reservations/vehicle
Content-Type: application/json

{
    "parkingSpotId": "00000000-0000-0000-0000-000000000001",
    "capacity": 2,
    "date": "2022-09-05",
    "employeeName": "Joe John",
    "licencePlate": "XYZ 1234"
}

###
POST {{url}}/reservations/cleaning
Content-Type: application/json

{
    "parkingSpotId": "00000000-0000-0000-0000-000000000001",
    "date": "2022-09-07"
}